### ISSUE TITLE
Redirect to interval server error page

### ISSUE THREAD

**Issue by anshul17khanna** [mansimarkaur/http-status#1]
Instead of displaying 'down' (status: 500), the page redirects to another page.

**Comment by mansimarkaur** [comment]
@anshul17khanna If the user enters a website that gives status code 500, the message "Unexpected condition encountered by the server is preventing it from fulfilling the request." is being displayed. I used the URL "http://httpbin.org/status/500" to check it. Were you talking about this or some other issue?

**Comment by anshul17khanna** [comment]
Try:
https://www.innovisionnsit.in/
http://nsit-moksha.com/
